### ISSUE TITLE
(BN(1000) * 1.2 * 1.2) - 1000 => 439.999999999

### ISSUE THREAD

**Issue by MouJiaoZi** [thenumbernine/lua-bignumber#1]
![img_v3_02bi_e4be32b9-dc9f-45a6-b632-fbb4ea2985bg](https://github.com/thenumbernine/lua-bignumber/assets/25788578/7bfa1b39-4f65-4aae-9dc5-f3dc92d12a0f)
![img_v3_02bi_ebb31720-e20d-4136-a709-de093185c71g](https://github.com/thenumbernine/lua-bignumber/assets/25788578/17ebf909-1b1a-4bbc-a051-abf90ed833b6)

**Comment by MouJiaoZi** [comment]
but, 
(BN(1000) * 12 * 12 / 100) - 1000 => 440
it's ok

**Comment by thenumbernine** [comment]
This isn't an issue with my library.
You are just discovering how floating-point numbers work.
``` Lua
> 1.2
1.2
> ('%.50f'):format(1.2)
1.19999999999999995559107901499373838305473327636719
```

This is exactly why I created the library: to work around this limitation of floating-point representation.
This library supports string-constructors and table-constructors, so you can avoid constructing a BigNumber from an imperfect fraction floating-point number:
``` Lua
> big'1.2'
1.2
> big{[-1]=2, [0]=1}
1.2
```
``` Lua
local BigNumber = require 'bignumber'
local a = BigNumber'1000' * BigNumber'1.2' * BigNumber'1.2'
print(a)    -- prints 1440
local b = a - 1000  -- subtraction using coerced float-point Lua-Number of 1000 is an exact representation and won't incur rounded fractions
print(b)    -- prints 440
```

**Comment by MouJiaoZi** [comment]
thank you so much!
